[project]
name = "pdf-chunker-vis"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "PyMuPDF>=1.23.0",
    "streamlit>=1.30.0",
    "data-prep-toolkit-transforms[docchunk,ededup,pdf2parquet]==1.1.0",
    "llama-index>=0.14.2",
]

[tool.setuptools.packages.find]
where = ["app"]
